package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FinanceInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "approvedBudget")
	private java.lang.Integer approvedBudget;
	@org.kie.api.definition.type.Label(value = "confirmation")
	private java.lang.Boolean confirmation;

	public FinanceInformation() {
	}

	public java.lang.Integer getApprovedBudget() {
		return this.approvedBudget;
	}

	public void setApprovedBudget(java.lang.Integer approvedBudget) {
		this.approvedBudget = approvedBudget;
	}

	public java.lang.Boolean getConfirmation() {
		return this.confirmation;
	}

	public void setConfirmation(java.lang.Boolean confirmation) {
		this.confirmation = confirmation;
	}

	public FinanceInformation(java.lang.Integer approvedBudget,
			java.lang.Boolean confirmation) {
		this.approvedBudget = approvedBudget;
		this.confirmation = confirmation;
	}

}