package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class POInformations implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "poNumber")
	private java.lang.Integer poNumber;
	@org.kie.api.definition.type.Label(value = "poDecription")
	private java.lang.String poDecription;
	@org.kie.api.definition.type.Label(value = "date")
	private java.util.Date date;

	public POInformations() {
	}

	public java.lang.Integer getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(java.lang.Integer poNumber) {
		this.poNumber = poNumber;
	}

	public java.lang.String getPoDecription() {
		return this.poDecription;
	}

	public void setPoDecription(java.lang.String poDecription) {
		this.poDecription = poDecription;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public POInformations(java.lang.Integer poNumber,
			java.lang.String poDecription, java.util.Date date) {
		this.poNumber = poNumber;
		this.poDecription = poDecription;
		this.date = date;
	}

}