package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VendorInformations implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "companyCode")
	private java.lang.String companyCode;
	@org.kie.api.definition.type.Label(value = "companyName")
	private java.lang.String companyName;
	@org.kie.api.definition.type.Label(value = "address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label(value = "phone")
	private java.lang.Integer phone;
	@org.kie.api.definition.type.Label(value = "email")
	private java.lang.String email;

	public VendorInformations() {
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	public java.lang.String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(java.lang.String companyName) {
		this.companyName = companyName;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.Integer getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.Integer phone) {
		this.phone = phone;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public VendorInformations(java.lang.String companyCode,
			java.lang.String companyName, java.lang.String address,
			java.lang.Integer phone, java.lang.String email) {
		this.companyCode = companyCode;
		this.companyName = companyName;
		this.address = address;
		this.phone = phone;
		this.email = email;
	}

}